### ISSUE TITLE
Add Algorithms 

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [WindhoverLabs/xtce_generator#23]
We need algorithms for calculating cfe_time telemetry.

**Comment by lorenzo-gomez-windhover** [comment]
At the moment this will be put in pause. If we do comeback to it, we could use the following for our YAML file:

```
          cfe_time:
            short_name: cfe_time
            long_name: Core Flight Executive - Time Services
            algorithms:
              custom:
                - name: TimeAlgo
                  language: Java
                  text: com.windhoverlabs.yamcs.algorithms.CFE_TIME$CFETime_Algorithm()
                  input_set:
                    - param_ref: CFE_TIME_DiagPacket_t.Payload.TimeSeconds
                    - param_ref: CFE_TIME_HkPacket_t2
                  output_set:
                    - param_ref: Time_Output
                    - param_ref: some_other_ref
                  trigger_set:
                    - on_param_update: CFE_TIME_HkPacket_t
                    - on_container_update: some_container_ref # Not supported in YAMCS at the moment
                    - on_periodic_update: 1 # In seconds
```
